### ISSUE TITLE
issues with DND5e 0.99

### ISSUE THREAD

**Issue by ExileofBrokenSky** [syl3r86/inventory-plus#15]
Seems since the new update some things have broken. Namely:
- Can't drag items into custom categories anymore
- While new categories can be created, they cannot be edited after creation, though deleting works.

**Comment by Ikabodo** [comment]
Yeah, noticed this too! I'm looking forward to this working again in the future. This is a great mod.

**Comment by Ikabodo** [comment]
`targetType = this.inventoryPlus.getItemType(item.data);`
is giving
`Uncaught (in promise) TypeError: Cannot read property 'data' of null`

**Comment by syl3r86** [comment]
this is fixed in inventory+ v0.3.1
