### ISSUE TITLE
Module Conflict/Feature Request: optionally use libWrapper

### ISSUE THREAD

**Issue by ardittristan** [syl3r86/inventory-plus#16]
Both 5esheet resourcesplus and inventory plus overwrite the 5eactorsheet.prototype.getData function making them not work with eachother. This could be mitigated if you support libwrapper, since then it should run both our patches.
You don't have to hard-require libwrapper for this, [how I did it with resourcesplus is](https://github.com/ardittristan/5eSheet-resourcesPlus/blob/master/addresources.js#L71):

```js
if (typeof libWrapper === "function") {
  // libwrapper way
} else {
  // normal way
}
```

[resourcesplus](https://github.com/ardittristan/5eSheet-resourcesPlus)
[libwrapper](https://github.com/ruipin/fvtt-lib-wrapper)

**Comment by syl3r86** [comment]
fixed in 0.3.2
