### ISSUE TITLE
Conflict with Resources Plus module

### ISSUE THREAD

**Issue by megahead11** [syl3r86/inventory-plus#18]
This module currently has a minor conflict with resources plus.
When checked with libWrapper, this is the conflict:
![image](https://user-images.githubusercontent.com/21242682/103451632-3a6f6780-4c7b-11eb-8697-99a771710cb3.png)

This conflict prevents custom containers from showing up or being added. When the module is disabled, custom categories re-appear and work as expected.

**Comment by syl3r86** [comment]
fixed in 0.3.2
