### ISSUE TITLE
broken on firefox

### ISSUE THREAD

**Issue by syl3r86** [syl3r86/inventory-plus#2]
firefox doesnt allow drag'n'drop without creating errors

**Comment by DivertedCircle** [comment]
I'm not even seeing the button to add a category on Firefox, and when used with Tidy5eSheet I get this error. The creator of the sheet indicated they believe this is an Inventory+ issue.
![image](https://user-images.githubusercontent.com/26470570/88572665-c4484400-cffc-11ea-8d46-434691d7b33d.png)

**Comment by syl3r86** [comment]
don't know what's happening with Tidy Sheet. I'm not supporting that in any way (yet).
I'm sorry to say but I'll have to get the module working on Firefox properly first, so you'll ahve to  be a bit patient. sry about that :(

**Comment by DivertedCircle** [comment]
The author of Tidy Sheet has posted that he added compatibility for Inventory+ however I'm guessing that doesn't work with Firefox. I don't mind waiting. Thanks!

**Comment by syl3r86** [comment]
should be fixed in v0.2
