### ISSUE TITLE
Cannot read property 'addInvenctoryFunctions' of undefined on FoundryVTT 0.8.6

### ISSUE THREAD

**Issue by p4535992** [syl3r86/inventory-plus#25]
**Environment Details**

Foundry VTT Version: 0.8.6

Operating System: \[Linux\]

How Are You Using Foundry: \[Linux,Native Application (Electron), Chrome\]

Which Game System: Dungeons and Dragons 5th Edition, version 1.3.3

Modules Enabled?: Yes

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

Module Version: 0.3.5

** Description of the issue: **

![img](https://i.imgur.com/hf4pAO4.png)

**Comment by ZeroXNoxus** [comment]
This issue seems to be fixed, please review.
