### ISSUE TITLE
Total weight for encumbrance is calculated without regard for item quantity.

### ISSUE THREAD

**Issue by kimitsu** [syl3r86/inventory-plus#5]
```463: customWeight += i.data.weight;``` should be ```463: customWeight += i.data.quantity * i.data.weight;```

**Comment by LadySaga** [comment]
I can confirm that weight still only counts once, and adding more or less doesn't update it. So I'm bumping this one up! :)

**Comment by syl3r86** [comment]
fixed in v0.3
