### ISSUE TITLE
BUG MINOR - Double icon show on the collapse button of the inventory tab with Tidy Sheet

### ISSUE THREAD

**Issue by p4535992** [syl3r86/inventory-plus#7]
**Environment Details:** 

Foundry VTT Version: 0.7.1
Operating System: [Linux]
How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]
Which Game System: Dungeons and Dragons 5th Edition, version 0.95
Modules Enabled?: yes
OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description of the issue:**

It's a very minor issue , the icon for the "collapse  button" compare two times when use the Tidy Sheet, here a screenshot :

![Imgur](https://i.imgur.com/XorP8Ef.png)

**Comment by syl3r86** [comment]
seems to be the same case as with https://github.com/syl3r86/inventory-plus/issues/9, so seems to no longer be an issue. let me know if there are still issues

**Comment by p4535992** [comment]
Yea its seem resolved on version 0.7.5 of Foundry. Ty very much.
