### ISSUE TITLE
Multiple Items Not Properly Adjusting Weight

### ISSUE THREAD

**Issue by ambrangelle** [syl3r86/inventory-plus#8]
[As shown in the image.](https://cdn.discordapp.com/attachments/133498557926735874/758483055852781638/1f774aca6eee2041fdd5e42eb087411c-png.png) you can see that although I have multiples of Chain mail, it isn't properly adjusting total carry weight.

**Comment by LadySaga** [comment]
I came here to report the same, but I think this is a duplicate of [this one](https://github.com/syl3r86/inventory-plus/issues/5) so, post your findings there. :)

**Comment by syl3r86** [comment]
fixed in v0.3
