### ISSUE TITLE
Conflicts with Tidysheet 5e

### ISSUE THREAD

**Issue by jenthura** [syl3r86/inventory-plus#9]
None of Inventory+ buttons appear on Tidysheet, but disabling, adding custom categories and then reenabling tidysheet works.

**Comment by syl3r86** [comment]
seems there were some changes to TidySheet that created, and fixed, those issues. let me know if you still have problems

**Comment by VladGrant** [comment]
Just a quick update on this. Seems like things work with TidySheet, however it does not looks like the custom categories appear at all now. Everything else seems to work fine.

**Comment by syl3r86** [comment]
fixed in 0.3.2
